# Generated by Django 3.1.6 on 2021-02-09 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name of hero')),
                ('hp', models.IntegerField(max_length=10, verbose_name='Health oint')),
                ('mana', models.IntegerField(max_length=10, verbose_name='Health oint')),
                ('fraction', models.CharField(max_length=100, verbose_name='Fraction')),
                ('atribute', models.IntegerField(choices=[(1, 'Streng'), (2, 'Agility'), (3, 'Intelligence')], verbose_name='Atribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
